export enum EnumButton {
  BACKSPACE = 'Backspace',
  CLEAR = 'C',
  SQUARE_ROOT = '√',
  PERCENT = '%',
  DIVIDE = '/',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9',
  MULTIPLY = '*',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SUBTRACT = '-',
  ONE = '1',
  TWO = '2',
  THREE = '3',
  ADD = '+',
  ZERO = '0',
  COUPLE_ZERO = '00',
  DECIMAL = ',',
  DECIMAL_CLONE = '.',
  EQUALS = '=',
}

export const calcButtons = [
  [EnumButton.BACKSPACE],
  [EnumButton.CLEAR, EnumButton.SQUARE_ROOT, EnumButton.PERCENT, EnumButton.DIVIDE],
  [EnumButton.SEVEN, EnumButton.EIGHT, EnumButton.NINE, EnumButton.MULTIPLY],
  [EnumButton.FOUR, EnumButton.FIVE, EnumButton.SIX, EnumButton.SUBTRACT],
  [EnumButton.ONE, EnumButton.TWO, EnumButton.THREE, EnumButton.ADD],
  [EnumButton.COUPLE_ZERO, EnumButton.ZERO, EnumButton.DECIMAL, EnumButton.EQUALS],
];
